# Setup
title: Edman P. Anjos
tagline: 'Virtual delusions of a young programmer'
description: 'Virtual delusions of a young programmer'
url: http://edman.github.io/
baseurl: /

author:
  name: 'Edman Paes dos Anjos'
  email: 'edmanjos@gmail.com'
  url: http://edman.github.io/

# Social links
github_username: 'edman'
github_repo: 'edman.github.io'
instagram_username: 'edman.anjos'
facebook_username: 'edman.anjos'

# Dependencies
# highlighter: pygments  # github does not support pygments

# Permalinks
permalink: '/:title'

# number of posts to be showed on the front page
paginate: 4
# format of pagination pages
paginate_path: 'page/:num'
# 'read more' delimiter
excerpt_separator: '<span class="more"/>'

show_drafts: true

exclude: [additionals]

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

