# Permalinks
# permalink:           pretty
permalink: '/:title'

# Setup
title:               Edman P. Anjos
tagline:             Virtual delusions of a young man
url:                 http://edman.github.io/
paginate:            2
# baseurl:             "http://edman.github.io/"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Edman Paes dos Anjos
  url:               https://twitter.com/mdo
  email:             edmanjos@gmail.com

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/edman/edman.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:
  About: '/about'
  Articles: '/articles'
  Feed: '/atom.xml'

# Use pygments for highlighting code snippets
highlight: pygments

